//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Hri
{
    [Serializable]
    public class JointQueryMsg : Message
    {
        public const string k_RosMessageName = "hri_msgs/JointQuery";
        public override string RosMessageName => k_RosMessageName;

        //  JointQuery.msg
        public Sensor.JointStateMsg start;
        public Sensor.JointStateMsg goal;

        public JointQueryMsg()
        {
            this.start = new Sensor.JointStateMsg();
            this.goal = new Sensor.JointStateMsg();
        }

        public JointQueryMsg(Sensor.JointStateMsg start, Sensor.JointStateMsg goal)
        {
            this.start = start;
            this.goal = goal;
        }

        public static JointQueryMsg Deserialize(MessageDeserializer deserializer) => new JointQueryMsg(deserializer);

        private JointQueryMsg(MessageDeserializer deserializer)
        {
            this.start = Sensor.JointStateMsg.Deserialize(deserializer);
            this.goal = Sensor.JointStateMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.start);
            serializer.Write(this.goal);
        }

        public override string ToString()
        {
            return "JointQueryMsg: " +
            "\nstart: " + start.ToString() +
            "\ngoal: " + goal.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
